ACT_STATE_INIT                  = 0
ACT_STATE_END                   = 0xFFFF

ACT_STATE_TREEVIEW_SELECT       = 1
ACT_STATE_CLICK_ADD_BUT         = 2
ACT_STATE_CLICK_DEL_BUT         = 3
ACT_STATE_CLICK_REC_BUT         = 4
ACT_STATE_EDIT_TITLE            = 5
ACT_STATE_EDIT_DETAIL           = 6
ACT_STATE_CLICK_UP_BUT          = 7
ACT_STATE_CLICK_DN_BUT          = 8
ACT_STATE_SWITCH_TO_BIN         = 9
ACT_STATE_SWITCH_BACK_FROM_BIN  = 10
