ACT_EVNT_INIT                  = 0
ACT_EVNT_END                   = 0xFFFF

ACT_EVNT_TREEVIEW_SELECT       = 1
ACT_EVNT_CLICK_ADD_BUT         = 2
ACT_EVNT_CLICK_DEL_BUT         = 3
ACT_EVNT_CLICK_REC_BUT         = 4
ACT_EVNT_EDIT_TITLE            = 5
ACT_EVNT_EDIT_DETAIL           = 6
ACT_EVNT_CLICK_UP_BUT          = 7
ACT_EVNT_CLICK_DN_BUT          = 8
ACT_EVNT_SWITCH_TO_BIN         = 9
ACT_EVNT_SWITCH_BACK_FROM_BIN  = 10
