ACT_EVNT_INIT                  = 0
ACT_EVNT_END                   = 0xFFFF

ACT_EVNT_TREEVIEW_SELECT       = 1
ACT_EVNT_ADD_NEW_TASK          = 2
ACT_EVNT_DEL_SELECT_TASK       = 3
ACT_EVNT_REC_ONE_TASK          = 4
ACT_EVNT_EDIT_TITLE            = 5
ACT_EVNT_EDIT_DETAIL           = 6
ACT_EVNT_MOVE_TASK_UP          = 7
ACT_EVNT_MOVE_TASK_DN          = 8
ACT_EVNT_SWITCH_TO_BIN         = 9
ACT_EVNT_SWITCH_BACK_FROM_BIN  = 10
ACT_EVNT_START_MAIN_LOOP       = 11
